### ISSUE TITLE
Glo -> GitKraken Boards

### ISSUE THREAD

**Issue by Mr-Wallet** [megos/gitkraken-i18n#123]
こんにちは、GitKraken開発者です。正式じゃなくて個人的な要請ですけど。^^;
Hi, GitKraken developer here. But this isn't an official request, I am making it personally. ^^;

ブランド変更されて全ての製品は「GitKraken Suite」に含まれます。これから「GitKraken Glo」は「GitKraken Boards」と呼ばれます。
We have changed our branding so that all our products are in the "GitKraken Suite". "GitKraken Glo" is now called "GitKraken Boards".

もしかして翻訳を更新されてくれませんか？よろしくお願いいたします！
Would you consider updating the translations? Thank you!

**Comment by megos** [comment]
@Mr-Wallet 

Hello, thank you for tell me changed brand names. My translation was outdated.
I updated Japanese translation this commit. (86eb34e2dba09352ff7f64006defb750d0b780a1)

Thank you as always for a very useful Git GUI Client. 
Although unofficial, i hope more use GitKraken for Japanese users by translating.
