### ISSUE TITLE
asar is not required in v6.1.0!

### ISSUE THREAD

**Issue by Mr-Wallet** [megos/gitkraken-i18n#89]
いつもGitKrakenの支援ありがとうございます。開発者の私たちはプレゼントをあげます。🙇

https://support.gitkraken.com/release-notes/current/ :
>An un-bundled version of GitKraken’s strings file has been added. Users can edit/replace for use in non-officially supported languages. This file can be located at {appLocation}/Resources/app.asar.unpacked/src/strings.json.

**Comment by megos** [comment]
@Mr-Wallet Awesome! Thank you!!
