### ISSUE TITLE
Can't move to each page of "Authentication"

### ISSUE THREAD

**Issue by SeaPants** [megos/gitkraken-i18n#97]
Moving <-Preference-> --> <-Authentication-> --> <:each page:> then occur crash everytime.
Maybe it's because some text isn’t translated into Japanese.

P.S. Thank you for your makes this mod. And, sorry for poor English.

**Comment by SeaPants** [comment]
#98 is hot-fixed this issue.
But it is not localized yet.

**Comment by megos** [comment]
@SeaPants   
Thank you for issue!  
Oops! That is certainly true..., but I have no idea to fix.  

Added caution readme. Thank you!

**Comment by SeaPants** [comment]
I confirmed that no problem in #100
Thank you for fix it!
